Traceback (most recent call last):
  File "lda_fit.py", line 32, in <module>
    lda_fit(args.featurefile, args.ncomponents, args.outputfile)
  File "lda_fit.py", line 26, in lda_fit
    fit = model.fit_transform(X)
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/decomposition/_lda.py", line 611, in fit
    X = self._check_non_neg_array(
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/decomposition/_lda.py", line 540, in _check_non_neg_array
    X = self._validate_data(X, reset=reset_n_features, accept_sparse="csr")
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/home/janneae/miniconda3/envs/cns/lib/python3.8/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
